name: Dart

on:
  push:
    branches: [ "main-test" ]
  pull_request:
    branches: [ "main-test" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
          channel: 'stable'

      - run: flutter test --coverage

      - name: Report LCOV
        uses: zgosalvez/github-actions-report-lcov@v1.5.0
        with:
          coverage-files: coverage/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: install lcov-badge2
        run: npm i -g lcov-badge2

      - name: create badge
        run: lcov-badge2 coverage/lcov.info

